### ISSUE TITLE
How to finetune the knowledge retrieval module?

### ISSUE THREAD

**Issue by BUAAPY** [Buki2/SLCO#1]
Excellent work! but could you please tell me where is the code to finetune the knowledge retrieval module?

**Comment by Buki2** [comment]
Thank you for your interest in our work. We have updated our guide on fine-tuning the pre-trained language model. [Here's the link](https://github.com/Buki2/SLCO#fine-tune-language-model).

If you have any further questions, please feel free to contact us :)

**Comment by BUAAPY** [comment]
Thanks a lot!
